---
#zenoh-config-path: "path"
ip: 224.0.0.224
port: 7441
topics:
    join_datafeed: join_datafeed
    join_algofeed: join_algofeed
    start_datafeed: start_datafeed
    start_algo: start_algo
    start_broker: start_broker
    abort_algo_subscriber: abort_algo_subscriber
    join_brokerfeed: join_brokerfeed
    join_algofeed_success: join_algofeed_success
    join_datafeed_success: join_datafeed_success
    strategy_list_request: strategy_list_request
    strategy_list_response: strategy_list_response
    strategies_from_dir_response: strategies_from_dir_response
